### ISSUE TITLE
Unable to install node: no match found for 6.15.1 in [6.16.0 6.17.0 8.15.0 8.15.1 9.11.2 10.15.1 10.15.2 11.10.0 11.10.1]

### ISSUE THREAD

**Issue by murmelsson** [SAP/cloud-sample-node-chat#3]
The reason I got this eponymous error, when trying to compile droplet using the `cf push` command, is that the node engine specified in package.json (6.15.1) is "too old".

So the quick solution to this issue, is what I did: changed the package.json so that the relevant entry for engine...node is, for example, 6.16.0, like this:

`"node": "6.16.0",`

After that, it compiles ok and the app runs on SCP fine.

I noted though, that quite soon, it may be necessary to specify a node version higher than 6.x, in the package.json, see this output snippet from successful compile run:

`-----> Installing binaries
       engines.node (package.json): 6.16.0
       engines.npm (package.json): 3.10.10
-----> Installing node 6.16.0
       Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-6.16.0-linux-x64-cflinuxfs3-45f43c54.tgz]
       **WARNING** node 6.x will no longer be available in new buildpacks released after 2019-04-30.
       See: https://github.com/nodejs/LTS
`

Have a nice day and best regards.
-dylan drummond

**Comment by murmelsson** [comment]
For example, I specified 

`"node": "10.15.2",`

so version 10.15.2, which is supported on the server side, worked just fine.

**Comment by indusankar89** [comment]
Hi Dyan,
Thanks for finding the issue, suggesting fix. 
edited the package.json to fetch the latest nodejs version. 
https://github.com/SAP/cloud-sample-node-chat/commit/de638c0e5e7b5c9f405776f294ebed8d441ed9cc

**Comment by eartherian** [comment]
Thanks for this thread.
In my case, I tried removing the entire "engines" section and got away with a cute little warning!
But the issue was solved.

![image](https://user-images.githubusercontent.com/9512605/64955688-89d32e00-d8a6-11e9-9c4f-c7d9e9d40cdb.png)

**Comment by usianej** [comment]
thank you
