### ISSUE TITLE
host in manifes.yml is deprecated

### ISSUE THREAD

**Issue by Joel0906** [SAP/cloud-sample-node-chat#4]
Hi Harini, The "host" in manifest.yml is deprecated and hence getting the error during CF push as  **"Deprecation warning: Route component attributes 'domain', 'domains', 'host', 'hosts' and 'no-hostname' are deprecated. Found: host"**

**Comment by indusankar89** [comment]
Hi Joel,
some versions of CLI still support host. https://github.com/cloudfoundry/cli/issues/1403 
you can fix the issue by removing the host parameter and adding random-route: true in the manifest.yml file.
