### ISSUE TITLE
String not found cf login

### ISSUE THREAD

**Issue by RafaelAndreati** [SAP/cloud-sample-node-chat#5]
Hello Guys
I'm new here, and I'm trying to launch an app on SAP Cloud Plataform however in order to do that I'd installed visual studio code, git, node.js and downloaded the sample node chat on this site. Already in the VSC I opened the project and at the route.js I clicked on "Terminal > New" then opened up a prompt in the bottom of the page and I wrote "cf login" as suggested but it been presented an error as the command is not recognized by the VSC. 
Did I forget to add anything or am I using the wrong language to the program recognize the command?

The error is attached if someone can help me solve this issue.

Kind regards,
Rafael Andreati
![VSC](https://user-images.githubusercontent.com/50306334/57201877-1d016c00-6f75-11e9-8543-9c67aa3891a1.PNG)

**Comment by indusankar89** [comment]
Hi Rafael, 

you might have to install CLI:
 https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/75125ef1e60e490e91eb58fe48c0f9e7.html#loio4ef907afb1254e8286882a2bdef0edf4

if the issue persists, please post it in discussions in the openSap course. https://open.sap.com/courses/cp1-3/sections/6zyT7puPhXLUlDpygrpACI/pinboard
